export const FETCHING_TASKS = "FETCHING_TASKS";
export const FETCHING_TASKS_SUCCESS = "FETCHING_TASKS_SUCCESS";
export const FETCHING_TASKS_FAIL = "FETCHING_TASKS_FAIL";
export const FETCHING_USER = "FETCHING_USER";
export const FETCHING_USER_SUCCESS = "FETCHING_USER_SUCCESS";
export const FETCHING_USER_FAIL = "FETCHING_USER_FAIL";
