export const FETCHING_TASKS = "FETCHING_TASKS";
export const FETCHING_TASKS_SUCCESS = "FETCHING_TASKS_SUCCESS";
export const FETCHING_TASKS_FAIL = "FETCHING_TASKS_FAIL";
export const FETCHING_USERS = "FETCHING_USERS";
export const FETCHING_USERS_SUCCESS = "FETCHING_USERS_SUCCESS";
export const FETCHING_USERS_FAIL = "FETCHING_USERS_FAIL";
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGING_IN = 'USER_LOGGING_IN';
